In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [62]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample_submission.csv')
test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [63]:
train1 = train
y_train = train1['label']
x_train = train1.drop(['label'],axis=1)

In [4]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [5]:
pred = knn.predict(test)

In [6]:
a = range(1,28001)
submission= pd.DataFrame({
    'ImageId': a,
    'Label': pred
})
#submission.set_index('ImageId',inplace=True)
submission.to_csv('submission.csv',index=False)

In [7]:
submission = pd.read_csv('submission.csv')
submission.tail()

ImageId  Label
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

In [8]:
sample.tail()

ImageId  Label
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [77]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten
from tensorflow.keras.optimizers import *
import tensorflow as tf
from tensorflow.keras import utils
from sklearn.model_selection import train_test_split


In [70]:
x_train = x_train.reshape(x_train.shape[0],28,28,1)
test = test.values.reshape(test.shape[0],28,28,1)
num_pix= x_train.shape[1]
x_train.shape

(42000, 28, 28, 1)

In [78]:
X_train, X_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1, random_state=42)


In [83]:
print('Integer-valued labels:')
print(y_train[:10])
y_train = utils.to_categorical(y_train, 10)
y_val = utils.to_categorical(y_val, 10)

Integer-valued labels:
22460    8
20828    5
32032    6
6194     2
12768    2
20041    7
20134    6
4265     1
35020    4
28843    7
Name: label, dtype: int64


In [84]:
print('One-hot labels:')
print(y_train[:10])

One-hot labels:
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [85]:
model = Sequential()

#model.add(Flatten(input_shape=x_train.shape[1:]))
model.add(Dense(num_pix,activation='relu'))
model.add(Dense(100,activation='relu'))
model.add(Dense(100,activation='relu'))
model.add(Dense(100,activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy')

In [86]:
model.fit(x=X_train, 
          y=y_train, 
          epochs=10,
          validation_data=(X_val, y_val), verbose=1
          )

Epoch 1/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.8287 - val_loss: 0.3868
Epoch 2/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.3094 - val_loss: 0.2755
Epoch 3/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.2384 - val_loss: 0.2666
Epoch 4/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.2015 - val_loss: 0.2182
Epoch 5/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.1773 - val_loss: 0.2138
Epoch 6/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.1567 - val_loss: 0.2322
Epoch 7/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.1486 - val_loss: 0.1995
Epoch 8/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.1349 - val_loss: 0.1887
Epoch 9/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.1236 - val_loss: 0.1989
Epoch 10/10
1182/1182 [==============================] - 2s 1ms/step - loss: 0.121

In [92]:
loss = pd.DataFrame(model.history.history)

In [93]:
loss.plot()

TypeError: no numeric data to plot

In [18]:
y_pred = model.predict(test)

In [19]:
y_pred

array([[ 2.4920640e+00,  2.5073028e+00,  2.4092498e+00, ...,
         2.2690942e+00,  2.3580177e+00,  2.1162395e+00],
       [-1.3275552e-01,  7.7444226e-02,  1.2638152e-02, ...,
         6.7861617e-02,  7.8401566e-03, -4.2693079e-02],
       [ 7.4917259e+00,  7.4935341e+00,  7.4613795e+00, ...,
         7.5358858e+00,  7.5426173e+00,  7.5074229e+00],
       ...,
       [ 3.3181639e+00,  3.3484061e+00,  3.2069814e+00, ...,
         3.4797659e+00,  3.2974563e+00,  3.2853363e+00],
       [ 9.3685551e+00,  9.3686266e+00,  9.3525410e+00, ...,
         9.4152622e+00,  9.4143534e+00,  9.3821564e+00],
       [ 2.0882945e+00,  2.1259837e+00,  2.0666103e+00, ...,
         2.3468082e+00,  2.2573905e+00,  2.2740455e+00]], dtype=float32)

In [97]:
results = model.predict(test)
results

array([[4.8621815e-11, 1.9852406e-07, 9.9997652e-01, ..., 1.4838169e-07,
        2.0356984e-07, 1.2016827e-15],
       [9.9992144e-01, 2.1191930e-15, 7.6844969e-08, ..., 3.5625400e-10,
        1.9860316e-10, 5.9817198e-06],
       [3.4786548e-04, 8.5740521e-06, 1.9900195e-04, ..., 2.0417892e-03,
        5.0483462e-03, 9.7874749e-01],
       ...,
       [1.2516331e-15, 2.4992983e-11, 6.8461382e-08, ..., 1.0899048e-07,
        3.2650110e-05, 5.2239925e-06],
       [7.7128198e-07, 3.4675762e-09, 5.5668443e-07, ..., 4.2242136e-05,
        1.1487115e-06, 9.9991107e-01],
       [5.5079861e-09, 9.8585690e-07, 9.9978274e-01, ..., 4.4898766e-06,
        1.6979075e-05, 1.1250787e-12]], dtype=float32)

In [94]:
results = np.argmax(results,axis = 1)
results = pd.Series(results,name="Label")


In [96]:
a = range(1,28001)
submission= pd.DataFrame({
    'ImageId': a,
    'Label': results
})
#submission.set_index('ImageId',inplace=True)
submission.to_csv('submission1.csv',index=False)